### ISSUE TITLE
key :readme not found 

### ISSUE THREAD

**Issue by milch** [JonGretar/ExDocDash#6]
Hi,

I am getting this above error when running ExDocDash on the newest version of Phoenix (1.0.2). Here is the full log:

```
* creating doc/Phoenix 1.0.2.docset/Contents/Resources/Documents/stylesheets/highlight.css
* creating doc/Phoenix 1.0.2.docset/Contents/Resources/Documents/stylesheets/icon-font.css
* creating doc/Phoenix 1.0.2.docset/Contents/Resources/Documents/stylesheets/normalize.css
* creating doc/Phoenix 1.0.2.docset/Contents/Resources/Documents/stylesheets/print.css
* creating doc/Phoenix 1.0.2.docset/Contents/Resources/Documents/stylesheets/screen.css
* creating doc/Phoenix 1.0.2.docset/Contents/Resources/Documents/javascripts/highlight.pack.js
* creating doc/Phoenix 1.0.2.docset/Contents/Resources/Documents/fonts/icomoon.eot
* creating doc/Phoenix 1.0.2.docset/Contents/Resources/Documents/fonts/icomoon.svg
* creating doc/Phoenix 1.0.2.docset/Contents/Resources/Documents/fonts/icomoon.ttf
* creating doc/Phoenix 1.0.2.docset/Contents/Resources/Documents/fonts/icomoon.woff
* creating doc/Phoenix 1.0.2.docset/icon.tiff
** (KeyError) key :readme not found in: %ExDoc.Config{extras: [], formatter: ExDocDash.Formatter.Dash, formatter_opts: [docset_docpath: "/vagrant/deps/phoenix/doc/Phoenix 1.0.2.docset/Contents/Resources/Documents", docset_root: "/vagrant/deps/phoenix/doc/Phoenix 1.0.2.docset", docset_sqlitepath: "/vagrant/deps/phoenix/doc/Phoenix 1.0.2.docset/Contents/Resources/docSet.dsidx"], homepage_url: nil, logo: nil, main: "Phoenix", output: "/vagrant/deps/phoenix/doc/Phoenix 1.0.2.docset/Contents/Resources/Documents", project: "Phoenix", retriever: ExDoc.Retriever, source_beam: "/vagrant/deps/phoenix/_build/docs/lib/phoenix/ebin", source_root: "/vagrant/deps/phoenix", source_url: "https://github.com/phoenixframework/phoenix", source_url_pattern: "https://github.com/phoenixframework/phoenix/blob/v1.0.2/%{path}#L%{line}", title: nil, version: "1.0.2"}
    lib/ex_doc_dash/formatter/dash.ex:25: ExDocDash.Formatter.Dash.run/2
    lib/mix/tasks/docs.dash.ex:44: Mix.Tasks.Docs.Dash.run/3
    (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:537: Enum.each/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
```

I am using `ex_doc` version `0.9.0`, `earmark` version `0.1.17` and the current master of ExDocDash.

**Comment by JonGretar** [comment]
Release 0.3.0 adds support for ex_doc <= 0.9.0
